---
# tasks file for run_docker_container
- name: Copy WebSite to Servers
  copy:
    src: "{{ source_file }}"
    dest: "{{ destination_file }}"
    mode: 0777

- name: Add private IP to index.htm
  shell: |
    cd /home/ubuntu/WebSite
    myip=`curl http://169.254.169.254/latest/meta-data/local-ipv4`
    echo $myip >> index.html


- name: Create apache container
  docker_container:
    name: apache
    image: httpd:2.4
    state: started
    recreate: yes
    volumes:
      - /home/ubuntu/WebSite:/usr/local/apache2/htdocs/
    published_ports:
      - "{{ apache_port }}:{{ apache_port }}"
