---
- name: Wait 600 seconds for target connection to become reachable/usable
  wait_for_connection:

- name: Install Docker and deploy site to container
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - install_docker
    - run_docker_container